# Generated by Django 4.0.1 on 2022-01-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='minimum_purchase',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
